### ISSUE TITLE
Date-Picker seems to store current Date -1 day to data base

### ISSUE THREAD

**Issue by agruenberg** [melohagan/budibase-component-kasper-date-picker#4] opened 2022-10-19 14:44 UTC
As you can see in the video, I selected the 13.10.2022, but the 12.10.2022 is stored in the data base.
[vokoscreen-2022-10-19_16-25-10.webm](https://user-images.githubusercontent.com/19472717/196723921-0a3eed9f-6f30-4690-ad4b-9d553a5ff5b6.webm)

**Comment by melohagan** [comment] 2022-10-21 15:16
Closed as duplicate of #3

**Closed as completed by melohagan** 2022-10-21 15:16 UTC
